In [1]:
import pandas as pd

# keras  - to build neural network like input layer , hidden layer and output layer - framework
# whenever we are using keras, tensorflow will work in backend to perform
# tensorflow - to process the neural network and gives output - framework

import tensorflow as ts
import numpy as np
from numpy import loadtxt

In [2]:
print(ts.__version__)  # tensorflow version installed

2.13.0


In [3]:
# import csv using load text 
# use delimiter (,) to separate using commas
data = loadtxt('diabetes2.csv', delimiter=',')     # Read the dataset
data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [4]:
data.shape

(768, 9)

In [5]:
X=data[:,0:8] #  in this case it wont take as 8 beacuse (n-1) so 8-1 = 7.. it takes till 7th column   # inputs

In [6]:
Y=data[:,8] # only targets or labels

In [7]:
Y # 0 - not attacked by diabetes   1 - attacked ie patient

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [8]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [9]:
# To split data for train and test
from sklearn.model_selection import train_test_split

In [10]:
xtrain, ytest, train_targets, test_targets = train_test_split(X,Y,test_size=0.25, random_state = 00)

In [11]:
xtrain.shape

(576, 8)

In [12]:
ytest.shape

(192, 8)

In [13]:
test_targets.shape

(192,)

In [14]:
ytest.shape

(192, 8)

In [15]:
# import keras to build neural networks
from keras.models import Sequential 
from keras.layers import Conv2D, MaxPool2D, Dense

In [16]:
model=Sequential()
model.add(Dense(8,input_dim=8, activation='relu'))   # input
model.add(Dense(8,activation='relu'))  #  hidden neuron
model.add(Dense(1, activation='sigmoid'))  # use sigmoid incase of output is 0 or 1/ true or false

In [17]:
# to compute loss

model.compile(loss='binary_crossentropy', optimizer='adam', metrics = ['accuracy'])

In [23]:
# Now train the model

model.fit(xtrain,train_targets, epochs=90, batch_size=10)      # epochs means how many times want to iterate the model

Epoch 1/90
58/58 [==============================] - 0s 973us/step - loss: 0.5576 - accuracy: 0.7188
Epoch 2/90
58/58 [==============================] - 0s 1ms/step - loss: 0.5664 - accuracy: 0.7222
Epoch 3/90
58/58 [==============================] - 0s 995us/step - loss: 0.5708 - accuracy: 0.7083
Epoch 4/90
58/58 [==============================] - 0s 966us/step - loss: 0.5622 - accuracy: 0.7170
Epoch 5/90
58/58 [==============================] - 0s 987us/step - loss: 0.5650 - accuracy: 0.7118
Epoch 6/90
58/58 [==============================] - 0s 948us/step - loss: 0.5565 - accuracy: 0.7118
Epoch 7/90
58/58 [==============================] - 0s 949us/step - loss: 0.5697 - accuracy: 0.7135
Epoch 8/90
58/58 [==============================] - 0s 913us/step - loss: 0.5638 - accuracy: 0.7083
Epoch 9/90
58/58 [==============================] - 0s 969us/step - loss: 0.5583 - accuracy: 0.7188
Epoch 10/90
58/58 [==============================] - 0s 1ms/step - loss: 0.5526 - accuracy: 0.7153
Epo

58/58 [==============================] - 0s 935us/step - loss: 0.5285 - accuracy: 0.7378
Epoch 83/90
58/58 [==============================] - 0s 890us/step - loss: 0.5290 - accuracy: 0.7309
Epoch 84/90
58/58 [==============================] - 0s 924us/step - loss: 0.5277 - accuracy: 0.7413
Epoch 85/90
58/58 [==============================] - 0s 956us/step - loss: 0.5289 - accuracy: 0.7378
Epoch 86/90
58/58 [==============================] - 0s 936us/step - loss: 0.5283 - accuracy: 0.7431
Epoch 87/90
58/58 [==============================] - 0s 863us/step - loss: 0.5271 - accuracy: 0.7431
Epoch 88/90
58/58 [==============================] - 0s 905us/step - loss: 0.5283 - accuracy: 0.7413
Epoch 89/90
58/58 [==============================] - 0s 845us/step - loss: 0.5288 - accuracy: 0.7378
Epoch 90/90
58/58 [==============================] - 0s 875us/step - loss: 0.5289 - accuracy: 0.7413


In [27]:
acc=model.evaluate(ytest,test_targets)
print('Accuracy score is:',acc)

6/6 [==============================] - 0s 2ms/step - loss: 0.5377 - accuracy: 0.7552
Accuracy score is: [0.5376900434494019, 0.7552083134651184]
